### ISSUE TITLE
Design database schema for maintaining a session

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/raise-it#17]
This task helps achieve user story #4

#### Task

Create a database schema for the mongodb database to store session information.

#### Acceptance Criteria

- [x] Include presenter information and some metadata
- [x] Include start date/time and end date/time
- [x] Include a session ID

**Comment by LeNPaul** [comment]
### session

session_id | session_name | host_name | state_date_time | end_date_time
