### ISSUE TITLE
Create endpoint for starting a session

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/raise-it#18]
This task helps achieve user story #4

#### Task

Create an endpoint that starts an active session when called with certain parameters

#### Acceptance Criteria

- [x] Accepts presenter information
- [x] Accepts session name (i.e. the name of the presentation) 
- [x] Creates a new document in the mongodb database for the session (database schema created in #17)
