### ISSUE TITLE
Create start session page

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/raise-it#19]
This task helps achieve user story #4

#### Task

Create a page that the presenter sees when they are about to start a session

#### Acceptance Criteria

- [x] Presenter sees this page when they navigate to start a new session from the home page
- [x] Presenter can enter session name
- [x] Presenter is able to enter in metadata for the session they are about to start
- [x] When they click on a button to start the session, this page mades an API request to start a session (endpoint created in #18)
