### ISSUE TITLE
Create home page

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/raise-it#2]
This task helps achieve user story #4 

#### Task

Create a home page that a user sees when they access the web application.

#### Acceptance Criteria

- [x] Need a nav bar with links to login and register
- [x] Need a basic footer
- [x] Need an option to either start a session (as the presenter) or join a session (as an audience member)
- [x] Include a short blurb describing the purpose of the web application

**Comment by LeNPaul** [comment]
Use this Bootstrap starter template: https://getbootstrap.com/docs/4.5/examples/starter-template/
