### ISSUE TITLE
Create session page for viewing a session as a presenter

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/raise-it#20]
This task helps achieve user story #6 

#### Task

Create a session page that the presenter sees when they are giving a presentation that will display the questions asked by audience members.

#### Acceptance Criteria

- [x] Create route for session page
- [x] Display questions asked by audience members for session
- [x] Create API for getting questions asked by audience members for session
- [x] Display session information (i.e. name, description, host information, etc.)
- [x] Create API for getting session information
