### ISSUE TITLE
Session page is regularly refreshed to show latest questions that have been submitted

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/raise-it#21]
This task helps achieve user story #6

#### Task

For the session page that is created in #20, the questions from the audience that are displayed will be regularly refreshed to show the latest questions asked.

#### Acceptance Criteria

- [x] Use Vue.js to regularly refresh only part of the page instead of the whole page
  - [x] New questions are automatically shown without refreshing the page
  - [x] Questions that are deleted are automatically removed without refreshing the page
