### ISSUE TITLE
Design database schema for storing questions from audience for a session

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/raise-it#22]
This task helps achieve user story #6 

#### Task

Create a database schema for the mongodb database to store information on questions asked for a session.

#### Acceptance Criteria

- [x] Store question text and id
- [x] Store parameter for specifying a question's rank
- [x] Store session_id
