### ISSUE TITLE
Group questions based on whether they have been marked as answered or not

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/raise-it#23]
This task helps achieve user story #5 

#### Task

On the session page, create a section for questions that have been marked as answered and a section for questions that have not been marked as answered, and display questions under their corresponding sections.

#### Acceptance Criteria

- [x] Create sections on the frontend for questions that are marked/unmarked
- [x] Divide the questions that have been queried from the `/session/questions/:session_id` endpoint into marked/unmarked groups
- [x] Regularly update the questions list for both marked/unmarked sections as questions are marked and unmarked
