### ISSUE TITLE
Clicking on a button for a question on the session page will mark or unmark that question as being answered

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/raise-it#24]
This task helps achieve user story #5 

#### Task

On the session page, for each question that has been submitted by the audience, the presenter can click on a button that will mark that question has being answered.

#### Acceptance Criteria

- [x] Create endpoint for updating the status of the question as being answered
- [x] Add button next to questions that have not been marked as answered for the presenter to mark as being answered
- [x] Clicking on the button for a question will make a request to the backend to mark that question as being answered
