### ISSUE TITLE
Clicking on a button on the presenter view of the session page will end the session

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/raise-it#26]
This task helps achieve user story #7

#### Task

When the presenter clicks on a button on the presenter view of the session page, the current session will be marked completed and the session will end.

#### Acceptance Criteria

- [x] Create a button on the frontend for ending the current session
- [x] When the button is clicked, an API request will be made to the appropriate endpoint to end the session
- [x] When the button to end a session is clicked, the presenter page will change to show that the session has ended
- [x] When the presenter page is loaded, the view will be different depending on if the session has ended or not
