### ISSUE TITLE
Audience members will not be able to submit new questions to a session that has been ended by the presenter 

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/raise-it#27]
This task helps achieve user story #7

#### Task

On the audience view of the session page, when the presenter ends the session, the audience will no long be able to submit new questions, and will see a prompt to indicate this.

#### Acceptance Criteria

- [x] Create frontend prompt that will indicate when a session has been ended by the presenter
- [x] Regularly poll the status of the current session
- [x] If the current session is marked as completed, then replace the new question input area with the prompt to indicate that the session has been ended by the presenter
