### ISSUE TITLE
Create frontend for audience to submit questions for an active session

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/raise-it#30]
This task helps achieve user story #14

#### Task

On the audience view of the session page, the audience will be able to input their question and then click a button to submit their question.

#### Acceptance Criteria

- [x] Create frontend text input and button for submitting question
- [x] When button is clicked the question is submitted to the session
- [x] Text area will be reset when the question is submitted
- [x] All audience members can see the submitted question
