### ISSUE TITLE
Refactor sessionApp to separate audience and presenter views

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/raise-it#33]
This task helps achieve user story #15

#### Task

Currently the sessionApp handles both the audience and presenter views. This should be refactored to separate concerns.

#### Acceptance Criteria

- [x] Create Vue.js application for presenter and audience views
- [x] Separate concerns from sessionApp between audience and presenter views
- [x] Questions should be ordered based on the number of votes
