### ISSUE TITLE
Create presenter dashboard page for viewing sessions started by the presenter when they are logged in as a user

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/raise-it#35]
This task helps achieve user story #9

#### Task

When a presenter is logged in as a user, they will be able to view all of the past sessions that they have started while they were logged in.

#### Acceptance Criteria

- [x] Create dashboard view for presenter when they are logged in
- [x] Create endpoint that returns past sessions started by a user
- [x] Dashboard view will display all past sessions that were started by the presenter while they were logged in
- [x] Create Vue.js application for managing user dashboard
