### ISSUE TITLE
Create route for viewing a past session

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/raise-it#37]
This task helps achieve user story #10

#### Task

From the user dashboard, the user can click on a session to view the questions that were submitted by the audience during that session.

#### Acceptance Criteria

- [x] Create page view for the session transcript
- [x] Session transcript view shows all questions that were submitted during that session
- [x] Clicking on the button to view a specific session will route to that session transcript page
